project:
  type: website
  output-dir: docs

website:
  title: "favoRite_resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - R_resources.qmd
      - Stats_resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

