---
title: "R Resources"
format: html
date-modified: last-modified
toc: true
toc-location: left
execute:
    eval: true
    echo: true
    warning: false
    error: true
---

# Troubleshooting help

-   [**Where to get help with your R question?**](https://masalmon.eu/2018/07/22/wheretogethelp/) - from Maelle Salmon's blog

-   [**Writing the perfect question**](https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/) - from Jon Skeet's coding blog

-   [**How to write a great reproducible example**](https://stackoverflow.com/a/5963610) - from a StackOverflow thread

------------------------------------------------------------------------

# Intro material

-   [**R basics, workspace and working directory, RStudio projects**](https://stat545.com/r-basics.html) - from STAT 545

-   [**What They Forgot to Teach You About R**](https://rstats.wtf/) - workshop materials by Jenny Bryan and Jim Hester

------------------------------------------------------------------------

# General Resources

-   [**Posit cheat sheets**](https://rstudio.github.io/cheatsheets/) - one-pagers for major packages. seriously, check them out.

-   [**RStudio keyboard shortcuts**](https://support.posit.co/hc/en-us/articles/200711853-Keyboard-Shortcuts)

    Some of my favorites are:

    -   `Ctrl` + `Enter`: run current line or selected code\
    -   `Ctrl` + `-`: the assignment operator (`<-`)\
    -   `Ctrl` + `Shift` + `c`: comment all selected lines (insert `#` in front)\
    -   `Ctrl` + `i`: re-indent selected code
    -   `Ctrl` + `Alt` + `i`: insert a code chunk into RMarkdown or Quarto file\
    -   `F2`: shows code used by function

-   [**Videos and Webinars from Posit**](https://posit.co/resources/videos/) - Several helpful webinars and presentations from past conferences.

# Communities

-   [**RStudio/Posit Community Forums**](https://community.rstudio.com/)- A very friendly place to ask questions

-   [**R4DS community**](https://www.rfordatasci.com/) - Be sure to join the slack community; it is also a very friendly place, with R book clubs!

-   [**ROpenSci**](https://ropensci.org/community/) - Their regular community calls are worth checking out

-   [**Tidy Tuesday**](https://github.com/rfordatascience/tidytuesday)- Weekly data visualization project; datasets provided on github and people share their graphics on social media

-   [**Ecology in R Facebook Group**](https://www.facebook.com/groups/ecologyinr/)

------------------------------------------------------------------------

# Free Online R Books and Resources

Some more specialized than others

## R and the `tidyverse` Generally

-   [**R For Data Science**](https://r4ds.hadley.nz/) , 2nd edition - by Hadley Wickham, Mine Cetinkaya-Rundel, and Garrett Grolemund

-   [**Hands-On Programming with R**](https://rstudio-education.github.io/hopr/) - by Garrett Grolemund

-   [**Getting used to R, RStudio, and R Markdown**](https://bookdown.org/chesterismay/rbasics/) - by Chester Ismay

-   [**ModernDive: Statistical Inference via Data Science**](https://moderndive.com/index.html) - by Chester Ismay and Albert Y. Kim. Don't let the title scare you; there's a lot in here about R and RStudio generally. It is also a helpful intro to stats.

-   [**Advanced R**](https://adv-r.hadley.nz/) , 2nd edition - by Hadley Wickham. You don't have to be truly advanced to benefit from this book.

-   [**R Packages**](http://r-pkgs.org) , 2nd edition - by Hadley Wickham and Jenny Bryan

## Workflow Tips

-   [**"Workflow" Chapter of R4DS**](https://r4ds.hadley.nz/workflow-scripts.html) - by Wickham, Cetinkaya-Rundel, and Grolemund
-   [**"Projects" Chapter of 'What They Forgot'**](https://rstats.wtf/projects) - from Jenny Bryan and Jim Hester. Talks specifically about working directories and Projects.
-   [**"Project-oriented workflow"**](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/) - blog post by Jenny Bryan

## Data Viz

-   [**Data Visualization: A Practical Introduction**](http://socviz.co/) - by Kieran Healy. Also a good intro to the `ggplot2` package; learn by doing.

-   [**Fundamentals of Data Visualization**](https://clauswilke.com/dataviz/) - by Claus O. Wilke

-   YouTube workshops from Thomas Lin Pederson ([\@thomasp85](https://twitter.com/thomasp85)), a software engineer at Posit and co-author of the `ggplot2` package (among other things). In 2020, he put on these impromptu workshops for beginner/intermediate R users:

    -   [**Part One (\~2.5 hours)**](https://www.youtube.com/watch?v=h29g21z0a68) is focused on the grammar of graphics and theory behind `ggplot2`
    -   [**Part Two (\~2 hours)**](https://www.youtube.com/watch?v=0m4yywqNPVY) discusses extension packages to the `ggplot2` universe (`gganimate` and `patchwork` for example)
    -   His materials are also available on [GitHub](https://github.com/thomasp85/ggplot2_workshop)

## R Markdown

-   [**R Markdown: The Definitive Guide**](https://bookdown.org/yihui/rmarkdown/) - by Yihui Xie, J.J. Allaire, and Garrett Grolemund

-   [**R Markdown Cookbook**](https://bookdown.org/yihui/rmarkdown-cookbook/) - by Yihui Xie, Christophe Dervieux, and Emily Riederer

## Quarto

-   [**Quarto.org**](https://quarto.org/) - the main website, with lots of tutorials and documention

-   [**Keynote Presentation: Hello, Quarto**](https://www.youtube.com/watch?v=p7Hxu4coDl8) - given by Mine Centinkaya-Rundel and Julia Stewart Lowndes at Posit::Conf 2023. Fantastic overview of the many things you can do in Quarto.

-   [**Tutorial: Hello, Quarto**](https://quarto.org/docs/get-started/hello/rstudio.html) - Web-based overview of Quarto

## Geospatial Data

-   [**Geocomputation with R**](https://r.geocompx.org/) - by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow. 2nd edition in progress.

-   [**Spatial Data Science**](http://r-spatial.org/book) - by Edzer Pebesma and Roger Bivand

## Version Control (Git and Github)

-   [**Happy Git with R**](http://happygitwithr.com) - online book by Jenny Bryan
-   [**GitHub tutorials**](https://kbroman.org/github_tutorial/) - from Karl Broman's blog

------------------------------------------------------------------------

# Statistics using R (books and resources)

## General stats

-   Book: [**Learning Statistics with R**](https://learningstatisticswithr.com) - by Danielle Navarro. Aimed at psychology researchers but has great motivating examples of why we even use statistics in the first place. Includes lots of clearly explained, worked examples using R code.

-   Book: [**ModernDive: Statistical Inference via Data Science**](https://moderndive.com/index.html) - by Chester Ismay and Albert Y. Kim.

## Ecological, Environmental, and/or Water Resources Statistics

-   Workshop: [**Introduction to Multivariate Data Analysis using vegan**](https://github.com/gavinsimpson/intro-vegan-webinar-july-2020) - by Gavin Simpson. `vegan` is an extremely popular package for running community analyses for ecology. Link is to GitHub repository with materials; that GitHub page links to the [recording on YouTube](youtu.be/tVnnG7mFeqA).

-   Workshop: [**Advanced Community Ecological Data Analysis using vegan**](https://github.com/gavinsimpson/advanced-vegan-webinar-july-2020) - by Gavin Simpson. Link is to GitHub repository with materials; that GitHub page links to the [recording on YouTube](youtu.be/PR1B_JkO49s).

-   Tutorial: [**GAMs in R**](https://noamross.github.io/gams-in-r-course/) - by Noam Ross. Helpful interactive overview of Generalized Additive Models, which are becoming popular in ecology and water resources analyses.

-   [**Gavin Simpson's blog**](https://fromthebottomoftheheap.net/blog/) has [many](https://fromthebottomoftheheap.net/2011/06/12/additive-modelling-and-the-hadcrut3v-global-mean-temperature-series/) [helpful](https://fromthebottomoftheheap.net/2016/03/25/additive-modeling-global-temperature-series-revisited/) [posts](https://fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/) on GAMs

-   Ben Bolker has put together a fantastic [**FAQ about mixed models**](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html)
